microsoft/playwright-mcp

README.md
First take on formatting install steps, please review and improve as needed.
=> Add VS Code installation links

README.md, src/index.ts, src/tools/snapshot.ts, tests/basic.spec.ts
Implemented `locator.selectOption`
=> feat(tool): add `locator.selectOption()` action

index.d.ts, src/context.ts, src/index.ts, src/program.ts, src/resources/console.ts, src/server.ts, src/tools/common.ts, src/tools/screenshot.ts, src/tools/snapshot.ts, src/tools/utils.ts, tests/fixtures.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/29
=> chore: use persistent profile by default

README.md
We set up some redirects so this works now.
=> Add VS Code install buttons

README.md, src/context.ts, src/index.ts, src/tools/common.ts, src/tools/screenshot.ts, src/tools/snapshot.ts, src/tools/utils.ts, tests/basic.spec.ts
Ref: https://github.com/microsoft/playwright-mcp/issues/39
=> chore: allow taking pixel screenshots in snapshot mode

.github/workflows/publish.yml
Requires the `NPM_TOKEN` secret to be set.
=> devops: add NPM publishing

README.md, src/program.ts
=> feat: sse transport

src/program.ts
Reverts microsoft/playwright-mcp#70
I was working on a bigger change and this conflicts.
=> Revert "fix: tired URL parsing bug"

src/context.ts, src/index.ts, src/program.ts, src/server.ts, tests/basic.spec.ts, tests/fixtures.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/84
=> chore: allow passing cdp endpoint

src/tools/common.ts, src/tools/utils.ts, tests/basic.spec.ts, tests/fixtures.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/96
=> chore: sanitize file path when saving

.github/workflows/ci.yml, src/context.ts, src/tools/screen.ts, src/tools/snapshot.ts, src/tools/tabs.ts, tests/cdp.spec.ts, tests/fixtures.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/164
=> chore: allow reusing tab over cdp

src/program.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/165
=> chore: default to headless when DISPLAY is missing

.gitignore, src/context.ts, src/javascript.ts, src/tools/keyboard.ts, src/tools/navigate.ts, src/tools/snapshot.ts, tests/basic.spec.ts, tests/cdp.spec.ts, tests/launch.spec.ts, tests/pdf.spec.ts
Closes https://github.com/microsoft/playwright-mcp/issues/163
=> feat: respond with action and generated locator

index.d.ts, src/index.ts, src/program.ts, src/server.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/186
=> chore: update exported types

README.md, src/context.ts, src/index.ts, src/tools/console.ts, tests/basic.spec.ts, tests/capabilities.spec.ts, tests/console.spec.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/168
=> chore: convert console resource to tool

config.d.ts, src/config.ts, src/tools/pdf.ts, src/tools/snapshot.ts, tests/fixtures.ts, tests/screenshot.spec.ts
Ref: https://github.com/microsoft/playwright-mcp/issues/279
=> chore: allow specifying output dir

config.d.ts, src/tools/snapshot.ts, tests/screenshot.spec.ts
Fixes: https://github.com/microsoft/playwright-mcp/issues/277
=> chore: allow configuring screenshot tool

config.d.ts, src/config.ts, src/context.ts, src/program.ts, src/tools/install.ts
Fixes: https://github.com/microsoft/playwright-mcp/issues/272
=> chore: allow configuring raw Playwright options

README.md
Fix the default path to User data directory
=> docs: Fix the default path to User data directory

README.md, src/config.ts, src/context.ts, src/program.ts, tests/device.spec.ts, utils/generate_links.js
Fixes https://github.com/microsoft/playwright-mcp/issues/294
=> chore: add support for device

Dockerfile
- Exclude unnecessary source files and development `node_modules` from the final image
- Switch runtime user from `root` to non-root `node` user
- Improve container security
- Minimize runtime privileges
=> Optimize Dockerfile by excluding unnecessary files and using non-root user

README.md, config.d.ts, index.d.ts, index.js, src/config.ts, src/connection.ts, src/index.ts, src/program.ts, src/tools.ts, src/tools/snapshot.ts, src/transport.ts, tests/fixtures.ts, tests/screenshot.spec.ts
Drive-by User-Agent sniffing and disabling of image type in Cursor.
=> chore: get rid of connection factory

.github/workflows/ci.yml, playwright.config.ts, tests/config.spec.ts, tests/files.spec.ts, tests/fixtures.ts, tests/headed.spec.ts, tests/network.spec.ts, tests/screenshot.spec.ts
https://github.com/microsoft/playwright-mcp/issues/346
=> test: run tests on MCP server inside Docker

src/tab.ts, tests/cdp.spec.ts, tests/config.spec.ts, tests/console.spec.ts, tests/core.spec.ts, tests/dialogs.spec.ts, tests/files.spec.ts, tests/launch.spec.ts, tests/network.spec.ts, tests/pdf.spec.ts, tests/request-blocking.spec.ts, tests/screenshot.spec.ts, tests/tabs.spec.ts, tests/testserver/index.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/376
=> chore: only reset network log upon explicit navigation

README.md
See [Microsoft MCR](https://mcr.microsoft.com/en-us/artifact/mar/playwright/mcp/about) for more information - not sure if its helpful to link to this page from the README?
Closes https://github.com/microsoft/playwright-mcp/issues/346
=> docs: reference to new Docker image

README.md, src/tools/common.ts, tests/capabilities.spec.ts, tests/wait.spec.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/389
=> feat(wait): allow waiting for given text

tests/fixtures.ts
Fixes https://github.com/microsoft/playwright-mcp/actions/runs/14940263450/job/41976152764#step:8:315
=> test: unflake 'should throw connection error and allow re-connecting'

README.md, config.d.ts, src/config.ts, src/context.ts, src/program.ts, src/tools/common.ts, tests/fixtures.ts, tests/launch.spec.ts
Ref: https://github.com/microsoft/playwright-mcp/issues/367
Ref: https://github.com/microsoft/playwright-mcp/issues/393
=> feat(ephemeral): allow for non-persistent context operation

src/pageSnapshot.ts, tests/cdp.spec.ts, tests/fixtures.ts, tests/tabs.spec.ts
Ref https://github.com/microsoft/playwright-mcp/issues/439
=> chore: fix operation over cdp

src/config.ts, tests/config.spec.ts, tests/fixtures.ts
Resolves https://github.com/microsoft/playwright-mcp/issues/458
=> fix: respect browserName in config

tests/library.spec.ts
Closes https://github.com/microsoft/playwright-mcp/issues/456
=> fix: import from cjs

config.d.ts, src/config.ts, src/connection.ts, src/context.ts, src/program.ts, src/tools/screenshot.ts, tests/screenshot.spec.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/449
=> fix(cursor): allow enforcing images for cursor --image-responses=allow

README.md
Add installation instructions for Claude Code CLI to the README.
=> docs: add Claude Code installation instructions

README.md
I just tried it out with Gemini CLI and it works like a charm, thanks for creating this MCP server!
=> Adding installation steps for Gemini CLI

README.md, package-lock.json, package.json, src/context.ts, src/tools.ts, src/tools/evaluate.ts, tests/capabilities.spec.ts, tests/fixtures.ts, utils/update-readme.js
Fixes https://github.com/microsoft/playwright-mcp/issues/424
=> chore: introduce browser_evaluate

extension/src/background.ts, extension/src/relayConnection.ts
* Remove debugger listeners if closed() is called as `ws.onclosed` is dispatched asynchronously
* Tabs can be closed while update badge command is in flight
* Inflight CDP commands fail if the tab closes, do not try to send their response to a closed socket
=> chore(extension): do not send if socket is already closed

src/tools/screenshot.ts, tests/screenshot.spec.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/817
=> chore: do not return fullPage screenshots to the LLM

src/tools/wait.ts, tests/wait.spec.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/859
=> fix: emit code for waitfor

src/browserContextFactory.ts, src/mcp/server.ts, src/program.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/869
=> chore: run test server per context

README.md
Showing some love for [opencode](https://github.com/sst/opencode) and adding installation instructions for it.
=> docs: Add opencode installation instructions

extension/src/ui/connect.css, extension/src/ui/connect.tsx, extension/tests/extension.spec.ts
=> chore: show download link on the status mismatch page

extension/tests/extension.spec.ts, src/extension/cdpRelay.ts, src/extension/extensionContextFactory.ts, src/program.ts
Fixes https://github.com/microsoft/playwright-mcp/issues/941
=> chore(extension): support custom executablePath

.github/workflows/ci.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml, package.json
Fixes https://github.com/microsoft/playwright-mcp/actions/runs/17521002811/job/49764720465
Fixes https://github.com/microsoft/playwright-mcp/issues/1014
=> devops: fix publishing

.github/workflows/publish.yml
https://github.com/microsoft/playwright/issues/37495
=> devops: migrate to OIDC NPM publishing

.github/workflows/publish.yml
https://github.com/microsoft/playwright/issues/37495
=> devops: do not use npm token

README.md
Added instructions for how to add the Playwright MCP to Warp. Very fun MCP to use btw. 😂
=> docs: add instructions for Warp
