src/context.ts
src/server.ts
tests/basic.spec.ts
tests/fixtures.ts

Fixes https://github.com/microsoft/playwright-mcp/issues/18

chore: restart browser if page closed manually

---

package.json

This PR updates the binary name in `package.json` from `mcp` to `mcp-server-playwright` as requested in issue #33. The change makes the binary name more specific, avoiding conflicts with other MCP servers and improving usability for global installations.
Fixes #33

Update binary name to mcp-server-playwright (fixes #33)

---

src/tools/snapshot.ts
src/tools/utils.ts
tests/basic.spec.ts

Resolves https://github.com/microsoft/playwright-mcp/issues/35 by stitching together aria snapshots for all frames into one. We can't build a proper tree because the ARIA snapshot doesn't contain iframe elements, but concatenating should work just fine for now.
Prompt I used for testing:
```
what jobs are on https://careers-changegrowlive.icims.com/jobs/
```

fix: stitch all frames into one snapshot

---

src/context.ts
src/tools/common.ts
src/tools/snapshot.ts
src/tools/utils.ts
tests/basic.spec.ts

As discussed:
- hides invisible frames from snapshot
- keep our own frame locator array, so we don't rely on `page.frames()` ordering to be stable

chore: only include visible iframes, keep frame locators in own array

---

src/program.ts

Closes https://github.com/microsoft/playwright-mcp/issues/67
When `req.headers.host` is defined, the URL parsing breaks because there's no protocol.

fix: tired URL parsing bug

---

.github/workflows/publish.yml

Similar to how we do it upstream: https://github.com/microsoft/playwright/blob/e2c8163b145d4a34f4585fc11a8a2643b9c94f98/utils/publish_all_packages.sh#L97
Reference: https://docs.npmjs.com/generating-provenance-statements

devops: use `--provenance` when publishing to NPM

---

package-lock.json
package.json
src/context.ts
tests/basic.spec.ts

Based on https://github.com/microsoft/playwright/pull/35396, we can now stitch the iframes into one tree.
I also changed from `.locator('html').ariaSnapshot()` to `.locator('body').ariaSnapshot()`, so we get a more compact tree.
Here's how it looks with `'html'`:
```yaml
- document [ref=s1e2]:
- heading "Hello" [level=1] [ref=s1e4]
- iframe [ref=s1e5]:
- document [ref=f1s1e2]:
- button "World" [ref=f1s1e4]
```
And here's with `'body'`:
```yaml
- heading "Hello" [level=1] [ref=s1e3]
- iframe [ref=s1e4]:
- button "World" [ref=f1s1e3]
```
If I was an LLM, i'd definitely prefer the second!

chore: stitch together iframes into one tree

---

.github/workflows/publish.yml

Like [upstream](https://github.com/microsoft/playwright/blob/3ad5c2731a3ccccbd8468ef14a88b1edd45867a4/.github/workflows/publish_release_npm.yml#L15) and in the [docs](https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow).

devops: fix npm publishing due to proverance

---

src/tools/common.ts
src/tools/screenshot.ts
src/tools/snapshot.ts
tests/basic.spec.ts

With current description it's hard to talk LLM into using `browser_press_key` instead of `browser_type`. This makes the following prompt work:
```
Goto https://app.utrsports.net/search?type=players"
Focus in the 'Search' box
Slowly type 'John'.
Wait for 'John' in the drop down list.
```

feat: add slowly option for typing one character at a time

---

README.md

Followup from https://github.com/microsoft/playwright-mcp/pull/42
That link works now.

chore: add back stable vscode install button

---

src/program.ts

The `StdioClientTransport` implementation sends SIGTERM upon calling `close()`, but it looks like they don't close the Stdin pipe. This PR adds `SIGTERM` and `SIGINT` signals as triggers to our exit routine.
Closes https://github.com/microsoft/playwright-mcp/issues/141
It's hard to test this because of https://github.com/modelcontextprotocol/typescript-sdk/issues/271, sadly.

fix: exit watchdog should listen for SIGINT/SIGTERM

---

package-lock.json

- Adds integrity hashes that were missing for 5 npm packages in `package-lock.json`
<hr />
Is there a reason hashes for some of these dependencies are missing from `package-lock.json`?
Right now these omissions prevent me from packaging a nix derivation for this mcp server directly off this repo (https://github.com/cameronfyfe/nix-mcp-servers/blob/main/pkgs/servers/mcp-server-playwright/default.nix#L17) and I was wondering if they might just be missing due to a bad merge or something odd like that at some point. `npm install` under normal use doesn't seem to care if the hashes are missing and installs the packages anyway, but it's a blocker for hermetic build systems like nix.
If this is intentional for some reason I'm not familiar with feel free to ignore and close.

Restore `package-lock.json` module hashes

---

examples.md
examples/write_regression_test.md
src/context.ts
tests/basic.spec.ts
tests/cdp.spec.ts
tests/tabs.spec.ts

Adding the "Playwright" keyword to the action output tells the LLM that it can use this code safely when coming up with a test. This gave me much better output for the example i've added here.
I'd like to keep a list of prompts in the `examples.md` file, both as a form of documentation, and as a reference for quality control.

chore: include "playwright" keyword, add examples

---

src/context.ts
src/tools/snapshot.ts
tests/capabilities.spec.ts

Pull request to allow taking screenshots of specific elements on the screen rather than the whole screen.
Also, changed the current screenshot taking to instead save the screenshot to a temp location. Doing this because the current implementation of returning an ImageContent result does not work with most MCP agents. This is also following the PDF implementation, which also exports to a file.
For large screenshots, it can also happen that the buffer is too large for agents, so saving to a file is preferred as to not lose the screenshot due to an image that is too big to be output in the chat.

Add element screenshot action for snapshots

---

src/context.ts
src/index.ts
src/server.ts
src/tools/common.ts
src/tools/console.ts
src/tools/dialogs.ts
src/tools/files.ts
src/tools/install.ts
src/tools/keyboard.ts
src/tools/navigate.ts
src/tools/pdf.ts
src/tools/screen.ts
src/tools/snapshot.ts
src/tools/tabs.ts
src/tools/tool.ts
tests/core.spec.ts
tests/launch.spec.ts
tests/pdf.spec.ts
tests/tabs.spec.ts
utils/update-readme.js

Moves the `schema.parse` call to the calling side of the handler, so we don't have to duplicate it everywhere.

chore: infer tool params

---

.gitignore

This commit adds .idea and .DS_Store to the .gitignore file to prevent these files from being tracked by Git. These files are typically generated by development environments and operating systems, and excluding them helps maintain a clean repository and avoid unnecessary commits.

chore(gitignore): Add .idea and .DS_Store to .gitignore

---

README.md
src/program.ts

This commit introduces a new `--host` option to the CLI, allowing users to specify the host address for the SSE server. The default value is `localhost`, and users can now bind the server to all interfaces by setting the host to `0.0.0.0`. This enhancement provides greater flexibility in server deployment, especially in environments where the server needs to be accessible from external networks.

feat(server): add host option to SSE server configuration

---

README.md

The commit fixes a syntax error in the `npx` command by removing
an extra backtick. It also improves the formatting by adding line
breaks before code blocks to enhance readability.

docs(readme): Fix syntax error and improve formatting

---

src/context.ts
tests/cdp.spec.ts
tests/fixtures.ts
tests/tabs.spec.ts

This fixes an issue that there were sticky launch errors. When the [following code path](https://github.com/microsoft/playwright-mcp/blob/a15f0f301b405c00e9987fd84bf0f1f1fe856125/src/context.ts#L307-L339) was throwing, the Error was stored in the Promise and not cleared afterwards, this meant:
- If a browser was not there and the user tried to install it via `browser_install` it was never working since the error was sticky.
- If other errors like CDP is not available yet etc. error appear a re-connect would not work - the MCP server would require a restart.
Test plan: Since we don't have any `browser_install` tests I added a CDP test for now to cover this bug.

fix: sticky launch errors

---

README.md
src/config.ts
src/program.ts
tests/screenshot.spec.ts

This PR introduces a CLI option to specify the `outputDir`. Users can now dynamically set the output directory via command-line arguments, enhancing flexibility and ease of configuration.
The motivation behind this change is to dynamically set the `outputDir` from within the program, allowing screenshots to be organized into different folders for each execution.
With this modification, it becomes possible to directly specify the `outputDir` through the CLI without needing to generate a configuration file beforehand.
- Added CLI parameter `--output-dir` to set the output directory.
```bash
npx @playwright/mcp@latest --outputDir /custom/path
```

Chore: Set `outputDir` via cli options

---

.github/workflows/publish.yml

https://github.com/microsoft/playwright-mcp/issues/346
Previously in our `microsoft/playwright` repository we run `docker build` and `docker push` commands manually. In this repository we use the [`docker/build-push-action` GitHub Action](https://github.com/docker/build-push-action) which seems to simplify that setup a lot. It also allows caching but I opted-out for now.

devops: add Docker publishing

---

.github/workflows/publish.yml

We don't do that for normal Playwright because we expect the user to mount/add/copy their own Playwright folder and there the version has to match. In this case publishing to `:latest` seems fine since its a isolated product.

devops: publish Docker image to :latest as well

---

src/tab.ts
src/tools/console.ts

Motivation: `console` is a global object in Node.js and having a method like that confuses intellisense.

chore: rename console to consoleMessages

---

tsconfig.json

Follow-up for https://github.com/microsoft/playwright-mcp/pull/385#discussion_r2081541865.
> `skipLibCheck`: Skip type checking all .d.ts files.

chore: unset skipLibCheck in tsconfig.json

---

README.md

Probably, `createServer` is not from `@playwright/mcp`.

Fix import in README from createServer to createConnection

---

README.md
tests/library.spec.ts

This test only worked with `--experimental-require-module`, which is only enabled by default on recent Node versions. Changing the test to use a dynamic import tests the same regression, but works on older versions.

chore: make library test run under older Node versions

---

README.md

The `createConnection` function returns an instance of the `Connection` class, which doesn't have a `connect` method. Updated the documentation to use `connection.server.connect(transport)` instead of `connection.connect(transport)` to match the actual implementation.
Related to #529

docs(readme): fix connection method call in programmatic usage example

---

README.md

Add the Cursor one-click instructions to the README.md

Include Cursor One-Click in README.md

---

.github/workflows/publish.yml

This tags the images we publish as EOL immediately in order to get excluded from the image scanning. Like we do upstream in microsoft/playwright.

devops(docker): enhance Docker image publishing with ORAS end-of-life tagging

---

README.md

[Goose](https://block.github.io/goose/) is a popular MCP client distributed by Block. This adds instructions to use playwright-mcp in Goose to the README

Add instructions to install in Goose

---

README.md

- Removed `noImageResponses` option in README configuration schema
- Add to use correct `imageResponses` option with proper type and description
- Aligned README documentation with actual `config.d.ts` interface
The README documentation contained an outdated `noImageResponses` boolean option. The correct option is `imageResponses` with three possible values as defined in [`config.d.ts:127`](https://github.com/microsoft/playwright-mcp/blob/main/config.d.ts#L127).

docs: Update README about imageResponses option.

---

README.md
src/tools/snapshot.ts
tests/core.spec.ts

Fixes https://github.com/microsoft/playwright-mcp/issues/652

feat(dblclick): add double click

---

src/tab.ts
src/tools/console.ts
tests/console.spec.ts
tests/core.spec.ts

Fixes https://github.com/microsoft/playwright-mcp/issues/669

chore: include page errors in console messages

---

src/context.ts
tests/dialogs.spec.ts

Fixes https://github.com/microsoft/playwright-mcp/issues/595

chore: resolve dialog races

---

README.md
config.d.ts
src/config.ts
src/context.ts
src/program.ts
tests/screenshot.spec.ts

Latest Cursor will suggest the right thing (to switch model)

chore: remove image reply special case in cursor

---

src/config.ts
src/program.ts

Fixes https://github.com/microsoft/playwright-mcp/issues/639

chore: mirror cli options w/ env vars

---

README.md
src/mcp/transport.ts
tests/http.spec.ts
tests/sse.spec.ts

Reverts microsoft/playwright-mcp#758
Sounds like the stock streamable implementation is to spec, so we can keep it.

Revert "chore: recommend sse by default"

---

README.md

Use the latest link from their website.
The current link in the README is returning a 404.
I got the new link from this page:
https://docs.cursor.com/en/tools/mcp

fix(cursor): Invalid MCP Install Link

---

README.md

This PR adds instructions to configure the playwright mcp with [openai codex](https://github.com/openai/codex); unlike the standard json config, codex uses TOML for configuration. 
More info at: https://github.com/openai/codex/blob/main/codex-rs/config.md#mcp_servers

docs: add instructions for installation in openai codex

---

README.md

Update README.md => Cursor manual setup instructions to use `@playwright/mcp@latest` for the command, vs. `@playwright/mcp`. 
Tested in Cursor 1.5.5
Why:
1.  Avoid pesky npx version issues, which may complicate some setups (see: https://github.com/npm/cli/issues/4108)
2. Remain consistent with pre-existing README.md guidance for installs - such as the below content: 
```
Standard config works in most of the tools:
e
{
"mcpServers": {
"playwright": {
"command": "npx",
"args": [
"@playwright/mcp@latest"
]
}
}
}
```

Consistency in README.md - Cursor manual install instructions should use @playwright/mcp@latest

---

config.d.ts

This PR adds the `sharedBrowserContext` configuration option.
The feature itself was already implemented in [[microsoft/playwright#37463](https://github.com/microsoft/playwright/pull/37463)](https://github.com/microsoft/playwright/pull/37463); this change only exposes the option so it can be enabled by users.
* Related issue: [[microsoft/playwright-mcp#1045](https://github.com/microsoft/playwright-mcp/issues/1045)](https://github.com/microsoft/playwright-mcp/issues/1045)
* Related PR: [[microsoft/playwright#37463](https://github.com/microsoft/playwright/pull/37463)](https://github.com/microsoft/playwright/pull/37463)
* Added the `sharedBrowserContext?: boolean` option in the configuration.
* No functional changes other than allowing users to enable the existing feature.

feat(config): add sharedBrowserContext option to reuse browser context across HTTP client

---

README.md

Expose the service on port 8931: 
```
docker run -d -i --rm --init --pull=always --entrypoint node --name playwright -p 8931:8931 "mcr.microsoft.com/playwright/mcp" cli.js --headless --browser chromium --no-sandbox --port 8931
```
The container is then reachable at http://localhost:8931/mcp.

Update README.md:  Running the Playwright-MCP server in docker
